### PR TITLE
S1-8812: chore(cis) port over our custom Ubuntu18.04-CIS changes

### PR DESCRIPTION
**Pull request by scott-rmd**
[S1-8812](https://remediant.atlassian.net/browse/S1-8812) - Port 18.04-CIS rmd specific changes to 20.04-CIS playbook

We had some custom work for the CIS module in 18.04 and want to preserve that work in 20.04.  Most of it surrounds specific controls in configuration as well as some triggers for things like iptables to refresh.

These changes are the byproduct of generating patches from the master 18.04 master repo:

 https://github.com/florianutz/Ubuntu1804-CIS @ 187ff8d5454328d6f9d90e947a5e267f09e76656

with our modified fork:

 https://github.com/Remediant/Ubuntu1804-CIS @ 0445ce6d2f6c96dd15d2f36dc29e213e69b8dc6d

and applying these patches to our Ubuntu 20.04 CIS fork:

 https://github.com/Remediant/ubuntu2004_cis @ 3a98f70988c6c2ffe94b1e50287ff1e36f2ad97c

Script to generate the patches

```
cd <path to Ubuntu18.04-CIS repo>
mkdir -p patches

for file in $(git diff --stat 187ff8d5454328d6f9d90e947a5e267f09e76656 0445ce6d2f6c96dd15d2f36dc29e213e69b8dc6d | tac | awk 'NR>1 {print $1}') ;
    do git diff 187ff8d5454328d6f9d90e947a5e267f09e76656 0445ce6d2f6c96dd15d2f36dc29e213e69b8dc6d -- "${file}" | sed 's/ubuntu1804cis/ubuntu2004cis/g' > patches/${file////_}.patch ;
done

```

And then apply the patches in the ubuntu2004_cis repo and manually reviewing rejections, failures, etc.

```
patch -p1 < ../Ubuntu1804-CIS/patches/<patch_name>
```

[S1-8812]: https://remediant.atlassian.net/browse/S1-8812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by scott-rmd** [comment]
@ivan-rmd there is still a need to update: https://github.com/Remediant/infrastructure/blob/develop/ansible/remediant/os-harden.yml to run this with the right optionset

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
> @ivan-rmd there is still a need to update: https://github.com/Remediant/infrastructure/blob/develop/ansible/remediant/os-harden.yml to run this with the right optionset

right, but changes there shouldn't affect how/if the CIS rules run; those options only need to to be customized for particular customers.

**Comment by scott-rmd** [comment]
>right, but changes there shouldn't affect how/if the CIS rules run; those options only need to to be customized for particular customers.

Correct.  Don't think its just on a per-customer basis either.  Rather its the entrypoint to running the ansible role.  But was just throwing it out to reinforce that.  I can actually drop the file in an infra pr that I was using.  We'll prolly have to change the naming scheme up a little bit.

**Comment by scott-rmd** [comment]
opened this PR with the focal play: https://github.com/Remediant/infrastructure/pull/694

**Pull request merged**
